sudo: required
language: ruby

matrix:
  include:
        
  - os: osx
    rvm: 2.5.1
    addons:
      chrome: beta
      firefox: "59.0.2"
    before_install:
    - sudo safaridriver --enable
    - gem install bundler -v 1.16.1

  #- os: osx
  #  rvm: 2.4.4
  #  addons:
  #    chrome: beta
  #    firefox: "59.0"
  #  before_install:
  #  - sudo bash ./spec/support/setup-chromedriver.sh
  #  - sudo bash ./spec/support/setup-geckodriver-alt.sh
  #  - sudo safaridriver --enable
  #  - sudo chromedriver --enable
  #  - sudo geckodriver --enable
  #  - gem install bundler -v 1.16.1
  #  script: xvfb-run bundle exec rake

  #- os: osx
  #  rvm: 2.3.7
  #  addons:
  #    chrome: beta
  #    firefox: "59.0"
  #  before_install:
  #  - sudo bash ./spec/support/setup-chromedriver.sh
  #  - sudo bash ./spec/support/setup-geckodriver-alt.sh
  #  - sudo safaridriver --enable
  #  - sudo chromedriver --enable
  #  - sudo geckodriver --enable
  #  - gem install bundler -v 1.16.1
  #  script: xvfb-run bundle exec rake
    
notifications: 
  email: false
