sudo: required
language: ruby
rvm:
  - 2.5.1
before_install:
  - sudo bash ./scripts/install-chromedriver.sh
  - sudo apt-get update -y && sudo apt-get install chromium-browser
  - gem install bundler -v 1.16.1
