sudo: required
language: ruby

matrix:
  include:

  - os: linux
    rvm: 2.6.0-preview1
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver.sh
    - gem install bundler -v 1.16.1
    script: xvfb-run bundle exec rake
  
  - os: linux
    rvm: 2.5.1
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver.sh
    - gem install bundler -v 1.16.1
    script: xvfb-run bundle exec rake

  - os: linux
    rvm: 2.4.4
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver.sh
    - gem install bundler -v 1.16.1
    script: xvfb-run bundle exec rake

  - os: linux
    rvm: 2.3.7
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver.sh
    - gem install bundler -v 1.16.1
    script: xvfb-run bundle exec rake
    
  - os: osx
    rvm: 2.5.1
    env:
      - MOZ_HEADLESS=1
    addons:
      chrome: beta
      firefox: latest
    before_install:
      - sudo bash ./spec/support/setup-chromedriver.sh
      - sudo bash ./spec/support/setup-geckodriver-alt.sh
      - sudo safaridriver --enable
      - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 &"
      - gem install bundler -v 1.16.1

  #- os: osx
  #  rvm: 2.4.4
  #  addons:
  #    chrome: beta
  #    firefox: latest
  #  before_install:
  #  - sudo bash ./spec/support/setup-chromedriver.sh
  #  - sudo bash ./spec/support/setup-geckodriver-alt.sh
  #  - sudo safaridriver --enable
  #  - sudo chromedriver --enable
  #  - sudo geckodriver --enable
  #  - gem install bundler -v 1.16.1
  #  script: xvfb-run bundle exec rake

  #- os: osx
  #  rvm: 2.3.7
  #  addons:
  #    chrome: beta
  #    firefox: latest
  #  before_install:
  #  - sudo bash ./spec/support/setup-chromedriver.sh
  #  - sudo bash ./spec/support/setup-geckodriver-alt.sh
  #  - sudo safaridriver --enable
  #  - sudo chromedriver --enable
  #  - sudo geckodriver --enable
  #  - gem install bundler -v 1.16.1
  #  script: xvfb-run bundle exec rake
    
notifications: 
  email: false
