sudo: required
language: ruby
rvm:
  - 2.5.1
before_install:
  - apt-get -qq update
  - apt-get install -y 
  - latest_chromedriver=$(wget -qO- http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - echo "#### Getting Chromedriver $latest_chromedriver ####"
  - wget https://chromedriver.storage.googleapis.com/${latest_chromedriver}/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - cp chromedriver /usr/bin/chromedriver
  - chown root /usr/bin/chromedriver
  - chmod +x /usr/bin/chromedriver
  - chmod 755 /usr/bin/chromedriver
  - rm chromedriver*
  - apt-get autoremove -y
  - gem install bundler -v 1.16.1
