sudo: required
language: ruby

matrix:
  include:
  
  - os: linux
    rvm: 2.5.1
    addons:
      chrome: stable
      firefox: "59.0.2"
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver.sh
    - gem install bundler -v 1.16.1
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    
  - os: linux
    rvm: 2.5.0
    addons:
      chrome: stable
      firefox: "59.0"
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver.sh
    - gem install bundler -v 1.16.1
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    
  - os: osx
    rvm: 2.5.1
    addons:
      chrome: beta
      firefox: "59.0.2"
    before_install:
    - sudo bash ./spec/support/setup-chromedriver.sh
    - sudo bash ./spec/support/setup-geckodriver-alt.sh
    - sudo safaridriver --enable
    - gem install bundler -v 1.16.1
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

  - os: osx
    rvm: 2.5.0
    addons:
      chrome: beta
      firefox: "59.0"
    before_install:
    - sudo bash ./spec/support/setup-chromedriver.sh
    - sudo bash ./spec/support/setup-geckodriver-alt.sh
    - sudo safaridriver --enable
    - gem install bundler -v 1.16.1
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    
notifications: 
  email: false
