sudo: required
language: ruby

matrix:
  include:
  # Testing all Available Ruby version from 2.3.7 - 2.6.0-preview1
  - os: linux
    rvm: 
      - 2.6.0-preview1
    env:
      - MOZ_HEADLESS=1
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver.sh
    - gem install bundler -v 1.16.1
  
  - os: linux
    rvm: 2.5.1
    env:
      - MOZ_HEADLESS=1
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver.sh
    - gem install bundler -v 1.16.1

  - os: linux
    rvm: 2.4.4
    env:
      - MOZ_HEADLESS=1
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver.sh
    - gem install bundler -v 1.16.1

  - os: linux
    rvm: 2.3.7
    env:
      - MOZ_HEADLESS=1
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver.sh
    - gem install bundler -v 1.16.1
    
  # OSX is only testing unsupported browser safari - all results should be pending
  - os: osx
    rvm: 2.5.1
    before_install:
      - sudo safaridriver --enable
      - gem install bundler -v 1.16.1
    script: bundle exec rake spec SPEC=spec/watir-performance-non-supported-browser_spec.rb

  - os: osx
    rvm: 2.4.4
    before_install:
      - sudo safaridriver --enable
      - gem install bundler -v 1.16.1
    script: bundle exec rake spec SPEC=spec/watir-performance-non-supported-browser_spec.rb
  
  - os: osx
    rvm: 2.3.7
    before_install:
      - sudo safaridriver --enable
      - gem install bundler -v 1.16.1
    script: bundle exec rake spec SPEC=spec/watir-performance-non-supported-browser_spec.rb

  #- os: linux with saucelabs to test Edge and IE
    
notifications: 
  email: false
