sudo: required
language: ruby

matrix:
  include:
  # Testing all Available Ruby version from 2.3.8 - 2.6.0
  - os: linux
    rvm: 2.6.0
    env:
      - MOZ_HEADLESS=1
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver-alt.sh
    - gem install bundler -v 2.0.1
  
  - os: linux
    rvm: 2.5.3
    env:
      - MOZ_HEADLESS=1
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver-alt.sh
    - gem install bundler -v 1.17.1
  
  - os: linux
    rvm: 2.5.2
    env:
      - MOZ_HEADLESS=1
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver-alt.sh
    - gem install bundler -v 1.17.1
    
  - os: linux
    rvm: 2.4.5
    env:
      - MOZ_HEADLESS=1
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver-alt.sh
    - gem install bundler -v 1.17.1

  - os: linux
    rvm: 2.3.8
    env:
      - MOZ_HEADLESS=1
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - bash ./spec/support/setup-chromedriver.sh
    - bash ./spec/support/setup-geckodriver-alt.sh
    - gem install bundler -v 1.17.1
    
  # OSX is only testing unsupported browser safari - all results should be pending
  - os: osx
    rvm: 2.6.0
    before_install:
      - sudo safaridriver --enable
      - gem install bundler -v 2.0.1
    script: bundle exec rake spec SPEC=spec/watir-performance-non-supported-browser_spec.rb

  - os: osx
    rvm: 2.5.3
    before_install:
      - sudo safaridriver --enable
      - gem install bundler -v 1.17.1
    script: bundle exec rake spec SPEC=spec/watir-performance-non-supported-browser_spec.rb
    
  - os: osx
    rvm: 2.5.2
    before_install:
      - sudo safaridriver --enable
      - gem install bundler -v 1.17.1
    script: bundle exec rake spec SPEC=spec/watir-performance-non-supported-browser_spec.rb

  - os: osx
    rvm: 2.4.5
    before_install:
      - sudo safaridriver --enable
      - gem install bundler -v 1.17.1
    script: bundle exec rake spec SPEC=spec/watir-performance-non-supported-browser_spec.rb
  
  - os: osx
    rvm: 2.3.8
    before_install:
      - sudo safaridriver --enable
      - gem install bundler -v 1.17.1
    script: bundle exec rake spec SPEC=spec/watir-performance-non-supported-browser_spec.rb

  #- os: linux with saucelabs to test Edge and IE
  #- os: linux
  #  rvm: 2.5.1
  #  env:
  #    - SAUCELABS=true
  #  addons:
  #    sauce_connect: true
  #  before_install:
  #    - gem install bundler -v 1.16.2
  #    - echo $SAUCELABS


notifications: 
  email: false
