os:
  - linux
  - osx

addons:
  chrome: stable
  safari: stable
  
sudo: required
language: ruby
rvm:
  - 2.5.1
  
before_install:
  - sudo safaridriver --enable
  - sudo chromedriver --enable
  # - sudo bash ./scripts/setup-chrome.sh remove
  - gem install bundler -v 1.16.1
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
